# Generated by Django 3.2.15 on 2022-11-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_myuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_Staff',
            field=models.BooleanField(default=False),
        ),
    ]
