# Generated by Django 3.2.15 on 2022-11-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_myuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_Staff',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_permissions',
        ),
    ]
