# Generated by Django 3.2.15 on 2022-11-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20221117_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'doctor'), ('nurse', 'nurse'), ('caregiver', 'caregiver'), ('physiotherapist', 'physiotherapist'), ('partner ', 'partner '), ('patient', 'patient')], default='patient', max_length=120),
        ),
    ]
