# Generated by Django 3.2.15 on 2022-11-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_myuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'doctor'), ('nurse', 'nurse'), ('caregiver', 'caregiver'), ('physiotherapist', 'physiotherapist'), ('partner ', 'partner '), ('patient', 'patient')], default='User', max_length=120),
        ),
    ]
