# Generated by Django 3.2.15 on 2022-11-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_myuser_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
