# Generated by Django 3.2.15 on 2022-10-31 19:03

from django.db import migrations, models
import django.utils.timezone
import partners.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareGiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=120, unique=True)),
                ('nid', models.CharField(max_length=120, null=True, unique=True)),
                ('working_area', models.CharField(max_length=120)),
                ('working_days', models.CharField(max_length=120)),
                ('qualicifacions', models.CharField(max_length=120, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=120)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=120, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=partners.models.upload_to_caregiver)),
                ('institution', models.TextField(blank=True, default='N/A', null=True)),
                ('short_description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Caregivers List',
            },
        ),
        migrations.CreateModel(
            name='DMF_Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=120, unique=True)),
                ('nid', models.CharField(max_length=120, null=True, unique=True)),
                ('qualicifacions', models.CharField(max_length=120)),
                ('specialty', models.CharField(max_length=120)),
                ('bmdc_regi_no', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('working_area', models.CharField(blank=True, default='N/A', max_length=120, null=True)),
                ('working_days', models.CharField(max_length=120)),
                ('working_times', models.CharField(max_length=120)),
                ('experience', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=120)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=partners.models.upload_to_doctor)),
                ('institution_or_chamber_address', models.TextField(blank=True, default='N/A', null=True)),
                ('short_description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Home call/Video Call DMF/CCP Doctors List',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=120, unique=True)),
                ('nid', models.CharField(max_length=120, null=True, unique=True)),
                ('qualicifacions', models.CharField(max_length=120)),
                ('specialty', models.CharField(max_length=120)),
                ('bmdc_regi_no', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('city', models.CharField(blank=True, default='N/A', max_length=500, null=True)),
                ('working_area', models.CharField(blank=True, default='N/A', max_length=120, null=True)),
                ('working_days', models.CharField(max_length=120)),
                ('working_times', models.CharField(max_length=120)),
                ('experience', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=120)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=partners.models.upload_to_doctor)),
                ('institution_or_chamber_address', models.TextField(blank=True, default='N/A', null=True)),
                ('short_description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Home call/Video Call Doctors List',
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=120, unique=True)),
                ('nid', models.CharField(max_length=120, null=True, unique=True)),
                ('qualicifacions', models.CharField(max_length=120)),
                ('working_area', models.CharField(max_length=120)),
                ('working_days', models.CharField(max_length=120)),
                ('working_times', models.CharField(max_length=120)),
                ('institution', models.TextField(blank=True, default='N/A', null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=120)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=120, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=partners.models.upload_to_nurse)),
                ('short_description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Nurse List',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(max_length=120, null=True)),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=120, unique=True)),
                ('service_provider_name', models.CharField(max_length=120, null=True)),
                ('service_provider_mobile', models.CharField(max_length=120, null=True)),
                ('nid', models.CharField(max_length=120, null=True, unique=True)),
                ('tred_licence', models.CharField(max_length=120, null=True, unique=True)),
                ('working_area', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=120)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=partners.models.upload_to_partner)),
                ('short_description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Partners (pharmacy) List',
            },
        ),
        migrations.CreateModel(
            name='Physiotherapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=120, unique=True)),
                ('nid', models.CharField(max_length=120, null=True, unique=True)),
                ('qualicifacions', models.CharField(max_length=120)),
                ('institution', models.CharField(max_length=120, null=True)),
                ('working_area', models.CharField(max_length=120)),
                ('working_days', models.CharField(max_length=120)),
                ('working_times', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=120)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=partners.models.upload_to_physiotherapist)),
                ('short_description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Physiotherapist List',
            },
        ),
    ]
