# Generated by Django 3.2.15 on 2023-03-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='cat',
            field=models.CharField(choices=[('none', 'none'), ('top', 'top')], default='none', max_length=120, null=True),
        ),
    ]
