# Generated by Django 3.2.15 on 2023-03-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_doctor_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fee_home_call',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
