# Generated by Django 3.2.15 on 2022-10-31 19:04

from django.db import migrations, models
import partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_dmf_doctor_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmf_doctor',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=partners.models.upload_to_doctor),
        ),
    ]
