# Generated by Django 3.2.15 on 2022-11-01 03:15

from django.db import migrations, models
import partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20221101_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmf_doctor',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=partners.models.upload_to_doctor),
        ),
    ]
