# Generated by Django 3.2.15 on 2022-11-04 04:37

from django.db import migrations, models
import partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_auto_20221104_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmf_doctor',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=partners.models.upload_to_doctor),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image_url',
            field=models.ImageField(null=True, upload_to=partners.models.upload_to_doctor),
        ),
    ]
