# Generated by Django 3.2.15 on 2022-11-04 19:27

from django.db import migrations, models
import partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_auto_20221104_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name_plural': 'Doctors List'},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='working_days',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='working_times',
        ),
        migrations.AddField(
            model_name='doctor',
            name='fee_chamber',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='fee_home_call',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='fee_video_call',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_days_chamber',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_days_home_call',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_days_video_call',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_times_chapber',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_times_home_call',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_times_video_call',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='dmf_doctor',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=partners.models.upload_to_doctor),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=120, null=True),
        ),
    ]
