# Generated by Django 3.2.15 on 2022-11-04 19:35

from django.db import migrations, models
import partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_auto_20221105_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='working_times_chapber',
            new_name='working_times_chamber',
        ),
        migrations.AlterField(
            model_name='dmf_doctor',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=partners.models.upload_to_doctor),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fee_chamber',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fee_home_call',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fee_video_call',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
