# Generated by Django 3.2.15 on 2022-11-06 09:26

from django.db import migrations, models
import partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_auto_20221105_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='payment_method',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='payment_number',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='dmf_doctor',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=partners.models.upload_to_doctor),
        ),
    ]
