# Generated by Django 3.2.15 on 2022-11-06 13:47

from django.db import migrations, models
import partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0014_auto_20221106_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dmf_doctor',
            options={'verbose_name_plural': 'DMF/CCP Doctors List'},
        ),
        migrations.RemoveField(
            model_name='dmf_doctor',
            name='working_days',
        ),
        migrations.RemoveField(
            model_name='dmf_doctor',
            name='working_times',
        ),
        migrations.AddField(
            model_name='dmf_doctor',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='dmf_doctor',
            name='fee_video_call',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='dmf_doctor',
            name='gender',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='dmf_doctor',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='dmf_doctor',
            name='working_days_home_call',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='dmf_doctor',
            name='working_days_video_call',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='dmf_doctor',
            name='working_times_chamber',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='dmf_doctor',
            name='working_times_home_call',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='dmf_doctor',
            name='working_times_video_call',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='dmf_doctor',
            name='image_url',
            field=models.ImageField(null=True, upload_to=partners.models.upload_to_dmp_doctor),
        ),
        migrations.AlterField(
            model_name='dmf_doctor',
            name='working_area',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
