# Generated by Django 3.2.15 on 2022-11-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0015_auto_20221106_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmf_doctor',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='fee_home_call',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='nid',
        ),
    ]
