# Generated by Django 3.2.15 on 2022-11-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0016_auto_20221106_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmf_doctor',
            name='bmdc_regi_no',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bmdc_regi_no',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
