# Generated by Django 3.2.15 on 2022-11-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0018_auto_20221107_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmf_doctor',
            name='bmdc_regi_no',
        ),
    ]
