# Generated by Django 3.2.15 on 2022-11-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0019_remove_dmf_doctor_bmdc_regi_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmf_doctor',
            name='fee',
        ),
    ]
