# Generated by Django 3.2.15 on 2022-11-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0020_remove_dmf_doctor_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmf_doctor',
            name='type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
