# Generated by Django 3.2.15 on 2022-11-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0021_alter_dmf_doctor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
