# Generated by Django 3.2.15 on 2022-12-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0022_alter_doctor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='working_area',
            field=models.CharField(max_length=2020),
        ),
    ]
