# Generated by Django 3.2.15 on 2022-12-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0023_alter_nurse_working_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='working_area',
            field=models.CharField(max_length=2020),
        ),
        migrations.AlterField(
            model_name='dmf_doctor',
            name='working_area',
            field=models.CharField(blank=True, max_length=2020, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='working_area',
            field=models.CharField(blank=True, max_length=2020, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='working_area',
            field=models.CharField(max_length=2020),
        ),
        migrations.AlterField(
            model_name='physiotherapist',
            name='working_area',
            field=models.CharField(max_length=2020),
        ),
    ]
