# Generated by Django 3.2.15 on 2022-09-27 11:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=120)),
                ('ans', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'FAQs ',
                'db_table': 'Faqs',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=api.models.upload_to_services)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Services',
                'db_table': 'Services',
            },
        ),
    ]
