# Generated by Django 3.2.15 on 2022-09-12 10:35

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('qualifications', models.TextField(null=True)),
                ('expericence', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('time', models.TextField(null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=api.models.upload_to_doctors)),
                ('category', models.CharField(max_length=100, null=True)),
                ('fee', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Doctors List',
                'db_table': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=120)),
                ('ans', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'FAGs List',
                'db_table': 'Faqs',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=api.models.upload_to_services)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Services List',
                'db_table': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120)),
                ('patient_age', models.CharField(max_length=120)),
                ('patient_phone', models.CharField(max_length=120)),
                ('details', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctors', verbose_name='Doctor ID')),
            ],
            options={
                'verbose_name_plural': 'Appointments List',
                'db_table': 'Appointments',
            },
        ),
    ]
