# Generated by Django 3.2.15 on 2023-01-23 07:27

import api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BmiFaqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=120)),
                ('ans', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'BMI FAQs ',
                'db_table': 'BmiFaqs',
            },
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=120)),
                ('ans', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'FAQs ',
                'db_table': 'Faqs',
            },
        ),
        migrations.CreateModel(
            name='GenaralInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('address', models.CharField(max_length=220)),
                ('email', models.CharField(max_length=220)),
                ('phone_1', models.CharField(max_length=16)),
                ('phone_2', models.CharField(max_length=16)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Genaral Information',
                'db_table': 'GenaralInformation',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=120, unique=True)),
                ('otp', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'OTP ',
                'db_table': 'OTP',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('path', models.CharField(blank=True, max_length=120, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=api.models.upload_to_services)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Services',
                'db_table': 'Services',
            },
        ),
        migrations.CreateModel(
            name='SMS_TOKEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=220)),
                ('status', models.CharField(max_length=120)),
                ('api_url', models.CharField(max_length=220, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'SMS TOKEN ',
                'db_table': 'SMS_TOKEN',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Doctors Speciality ',
            },
        ),
    ]
