# Generated by Django 3.2.15 on 2023-03-24 12:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalGuidelines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('paper', models.FileField(upload_to=api.models.upload_to_pdf)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Journal Guidelines',
                'db_table': 'JournalGuidelines',
            },
        ),
    ]
