# Generated by Django 3.2.15 on 2022-11-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenaralInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('address', models.CharField(max_length=220)),
                ('email', models.CharField(max_length=220)),
                ('phone_1', models.CharField(max_length=16)),
                ('phone_2', models.CharField(max_length=16)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Genaral Information',
                'db_table': 'GenaralInformation',
            },
        ),
    ]
