# Generated by Django 3.2.15 on 2022-09-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=120)),
                ('otp', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'OTP ',
                'db_table': 'OTP',
            },
        ),
    ]
