# Generated by Django 3.2.15 on 2022-10-01 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS_TOKEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=220)),
                ('status', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'SMS TOKEN ',
                'db_table': 'SMS_TOKEN',
            },
        ),
        migrations.AddField(
            model_name='otp',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
