# Generated by Django 3.2.15 on 2022-11-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_genaralinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='path',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
