# Generated by Django 3.2.15 on 2022-09-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_callappointments_calldoctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldoctors',
            name='number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
