# Generated by Django 3.2.15 on 2023-01-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_services_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Doctors Speciality ',
            },
        ),
    ]
