# Generated by Django 3.2.15 on 2023-01-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='BmiFaqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=120)),
                ('ans', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'BMI FAQs ',
                'db_table': 'BmiFaqs',
            },
        ),
    ]
