# Generated by Django 3.2.15 on 2023-01-03 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('fee', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=services.models.upload_to_diagnostic)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('payment_method', models.CharField(choices=[('Bkash', 'Bkash'), ('Nogod', 'Nogod'), ('Rocket', 'Rocket'), ('Upay', 'Upay')], default='Bkash', max_length=120)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'unpaid'), ('pending', 'pending'), ('paid', 'paid')], default='unpaid', max_length=120)),
                ('service_status', models.CharField(choices=[('pending', 'pending'), ('cancelled', 'cancelled'), ('completed', 'completed'), ('approved', 'approved')], default='pending', max_length=120)),
                ('address', models.TextField()),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Home Diagnostic',
            },
        ),
    ]
