# Generated by Django 3.2.15 on 2023-01-07 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_homemedicine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnostic',
            options={'verbose_name_plural': 'Mobile Diagnostic'},
        ),
    ]
