# Generated by Django 3.2.15 on 2023-01-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20230121_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostic',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='homemedicine',
            old_name='user_id',
            new_name='user',
        ),
    ]
