# Generated by Django 3.2.15 on 2023-01-22 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0024_auto_20221207_1010'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorsappointment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='doctorsappointment',
            name='doctor_id',
        ),
        migrations.AddField(
            model_name='doctorsappointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='partners.doctor', verbose_name='Doctor'),
        ),
    ]
