# Generated by Django 3.2.15 on 2022-11-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20221119_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsappointment',
            name='payment_method',
            field=models.CharField(choices=[('Bkash', 'Bkash'), ('Nogod', 'Nogod'), ('Rocket', 'Rocket'), ('Upay', 'Upay')], default='pending', max_length=120),
        ),
        migrations.AddField(
            model_name='doctorsappointment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
