# Generated by Django 3.2.15 on 2022-11-20 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0003_auto_20221119_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsappointment',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='doctorsappointment',
            name='payment_method',
            field=models.CharField(choices=[('Bkash', 'Bkash'), ('Nogod', 'Nogod'), ('Rocket', 'Rocket'), ('Upay', 'Upay')], default='Bkash', max_length=120),
        ),
    ]
