# Generated by Django 3.2.15 on 2022-11-27 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0022_alter_doctor_experience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0004_auto_20221120_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsappointment',
            name='doctor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='doctorsappointment',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
