# Generated by Django 3.2.15 on 2022-11-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20221127_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsappointment',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'unpaid'), ('pending', 'pending'), ('paid', 'paid')], default='unpaid', max_length=120),
        ),
        migrations.AlterField(
            model_name='doctorsappointment',
            name='service_status',
            field=models.CharField(choices=[('pending', 'pending'), ('cancelled', 'cancelled'), ('completed', 'completed'), ('approved', 'approved')], default='pending', max_length=120),
        ),
    ]
