# Generated by Django 3.2.15 on 2022-12-28 13:14

import appointment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_remove_medicine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=appointment.models.upload_to_medicine),
        ),
    ]
