# Generated by Django 3.2.15 on 2023-01-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_medicine_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsappointment',
            name='service_status',
            field=models.CharField(choices=[('pending', 'pending'), ('cancelled', 'cancelled'), ('completed', 'completed'), ('approved', 'approved')], default='approved', max_length=120),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='fee',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
