# Generated by Django 3.2.15 on 2022-09-27 10:38

import Videocall_Expert_Doctor.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCallExpertDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('qualifications', models.TextField(null=True)),
                ('expericence', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('time', models.TextField(null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=Videocall_Expert_Doctor.models.upload_to_doctors)),
                ('speciality', models.CharField(max_length=100, null=True)),
                ('fee', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Video Call Expert Doctors',
                'db_table': 'VideoCallExpertDoctor',
            },
        ),
        migrations.CreateModel(
            name='VideoCallExpertDoctorsAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120)),
                ('patient_age', models.CharField(max_length=120)),
                ('patient_phone', models.CharField(max_length=120)),
                ('details', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Videocall_Expert_Doctor.videocallexpertdoctor', verbose_name='Doctor')),
            ],
            options={
                'verbose_name_plural': 'Video Call Expert Doctor Appointment',
                'db_table': 'VideoCallExpertDoctorsAppointment',
            },
        ),
    ]
