# Generated by Django 3.2.15 on 2023-01-19 11:57

import blog.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('keywords', models.CharField(max_length=120)),
                ('image_url', models.ImageField(upload_to=blog.models.upload_to_blog)),
                ('short_desc', models.TextField()),
                ('desc', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Blog Post',
                'db_table': 'Blog',
            },
        ),
    ]
