# Generated by Django 3.2.15 on 2023-07-06 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advices', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Advices',
                'db_table': 'Advices',
            },
        ),
        migrations.CreateModel(
            name='ChiefComplaient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaient', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Chief Complaient',
                'db_table': 'ChiefComplaient',
            },
        ),
        migrations.CreateModel(
            name='Diagosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagosis', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Diagosis',
                'db_table': 'Diagosis',
            },
        ),
        migrations.CreateModel(
            name='Examinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examinations', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Examinations',
                'db_table': 'Examinations',
            },
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Followup',
                'db_table': 'Followup',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'History',
                'db_table': 'History',
            },
        ),
        migrations.CreateModel(
            name='Investigations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigations', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Investigations',
                'db_table': 'Investigations',
            },
        ),
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.TextField()),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Prescriptions',
            },
        ),
    ]
