# Generated by Django 3.2.15 on 2023-04-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
