# Generated by Django 3.2.15 on 2022-09-27 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Specialist_Doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistdoctorsappointment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Specialist_Doctors.specialistdoctor', verbose_name='name'),
        ),
    ]
