# Generated by Django 3.2.15 on 2022-09-27 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Specialist_Doctors', '0002_alter_specialistdoctorsappointment_doctor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialistdoctor',
            old_name='number',
            new_name='mobile',
        ),
        migrations.AlterField(
            model_name='specialistdoctorsappointment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Specialist_Doctors.specialistdoctor', verbose_name='Doctor'),
        ),
    ]
