# Generated by Django 3.2.15 on 2022-09-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Specialist_Doctors', '0003_auto_20220927_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialistdoctor',
            options={'verbose_name_plural': 'Specialist Doctors'},
        ),
    ]
