# Generated by Django 3.2.15 on 2023-01-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
